# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway

media_folder: "public/uploads" # Path to where uploaded files will be stored in your repo
public_folder: "/uploads" # Path users will access the files from on the deployed site

i18n:
  structure: multiple_folders
  locales: [en, fr, de, pt]

collections:
  - name: "settings"
    label: "Settings"
    files:
      - name: "settings"
        label: "Site Settings"
        file: "src/data/settings.json"
        i18n: true
        fields:
          - { label: "Site Title", name: "title", widget: "string", i18n: true }
          - { label: "Site Description", name: "description", widget: "text", i18n: true }
          - { label: "Site URL", name: "siteUrl", widget: "string" }
          - { label: "Site Logo", name: "logo", widget: "image" }
          - { label: "Site Favicon", name: "favicon", widget: "image" }
          - { label: "Site Navigation", name: "navigation", widget: "list", i18n: true, fields: [
              { label: "Title", name: "title", widget: "string" },
              { label: "URL", name: "url", widget: "string" }
            ]
          }
  - name: "homepage"
    label: "Homepage - content"
    folder: "src/pages/homepage"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.html" }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - { label: "Image", name: "image", widget: "image", i18n: true }
  - name: "about-us"
    label: "About Us - content"
    folder: "src/pages/about-us"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.html" }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - { label: "Image", name: "image", widget: "image", i18n: true }
  - name: "mission"
    label: "Mission"
    folder: "src/pages/mission"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.html" }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - { label: "Image", name: "image", widget: "image", i18n: true }
  - name: "sponsorship"
    label: "Sponsorship"
    folder: "src/pages/sponsorship"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.html" }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - { label: "Image", name: "image", widget: "image", i18n: true }
  - name: "get-involved"
    label: "Get Involved"
    folder: "src/pages/get-involved"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.html" }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - { label: "Image", name: "image", widget: "image", i18n: true }
  - name: "pages" # Used in routes, e.g., /admin/collections/pages
    label: "Pages" # Used in the UI
    folder: "src/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    i18n: true
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.html" }
      - { label: "Page-Title", name: "pagetitle", widget: "string", i18n: true }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Subtitle", name: "subtitle", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime", i18n: duplicate }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/posts/blog" # The path to the folder where the documents are stored  
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    i18n: true
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/blog.njk" }
      - { label: "Title", name: "title", widget: "string", i18n: true}
      - { label: "Tags", name: "tags", widget: "list", default: "education" }
      - { label: "Publish Date", name: "date", widget: "datetime",i18n: duplicate }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number", default: 5, i18n: duplicate }
      - { label: "Summary", name: "summary",widget: "markdown", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
